version: "3"
services:
    namenode:
      image: apache/hadoop:3
      hostname: namenode
      command: ["hdfs", "namenode"]
      privileged: true
      ports:
        - 9870:9870
      env_file:
        - ./config
      environment:
          ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
    datanode_a:
      image: apache/hadoop:3
      command: ["hdfs", "datanode"]
      privileged: true
      env_file:
        - ./config     
      hostname: datanode_a
    
    datanode_b:
      image: apache/hadoop:3
      command: ["hdfs", "datanode"]
      privileged: true
      env_file:
        - ./config
      hostname: datanode_b

    datanode_c:
      image: apache/hadoop:3
      command: ["hdfs", "datanode"]
      privileged: true
      env_file:
        - ./config
      hostname: datanode_c

    datanode_d:
      image: apache/hadoop:3
      command: ["hdfs", "datanode"]
      privileged: true
      env_file:
        - ./config
      hostname: datanode_d
    
    resourcemanager:
      image: apache/hadoop:3
      hostname: resourcemanager
      command: ["yarn", "resourcemanager"]
      privileged: true
      ports:
         - 8088:8088
      env_file:
        - ./config
      volumes:
        - ./test.sh:/opt/test.sh
        
    nodemanager:
      image: apache/hadoop:3
      command: ["yarn", "nodemanager"]
      privileged: true
      env_file:
        - ./config